### ISSUE TITLE
Towards AiiDA 2.0

### ISSUE THREAD

**Issue by yakutovicha** [JuDFTteam/aiida-fleur#120]
I ran aiida-common-workflows against the `develop` branch of AiiDA which contains some backwards-incompatible changes to be released in AiiDA 2.0.

Here is the issue that I encountered:

```python
 | [1746|FleurinputgenCalculation|on_except]: Traceback (most recent call last):
 |   File "/home/max/.virtualenvs/aiida/lib/python3.7/site-packages/plumpy/process_states.py", line 230, in execute
 |     result = self.run_fn(*self.args, **self.kwargs)
 |   File "/home/max/codes/aiida-core/aiida/engine/processes/calcjobs/calcjob.py", line 388, in parse
 |     exit_code_retrieved = self.parse_retrieved_output(retrieved_temporary_folder)
 |   File "/home/max/codes/aiida-core/aiida/engine/processes/calcjobs/calcjob.py", line 468, in parse_retrieved_output
 |     exit_code = parser.parse(**parse_kwargs)
 |   File "/home/max/.virtualenvs/aiida/lib/python3.7/site-packages/aiida_fleur/parsers/fleur_inputgen.py", line 89, in parse
 |     fleurinp = FleurinpData(files=[inpxml_file], node=output_folder)
 |   File "/home/max/.virtualenvs/aiida/lib/python3.7/site-packages/aiida_fleur/data/fleurinp.py", line 111, in __init__
 |     self.set_files(files, node=node)
 |   File "/home/max/.virtualenvs/aiida/lib/python3.7/site-packages/aiida_fleur/data/fleurinp.py", line 182, in set_files
 |     self.set_file(file1, node=node)
 |   File "/home/max/.virtualenvs/aiida/lib/python3.7/site-packages/aiida_fleur/data/fleurinp.py", line 191, in set_file
 |     self._add_path(filename, dst_filename=dst_filename, node=node)
 |   File "/home/max/.virtualenvs/aiida/lib/python3.7/site-packages/aiida_fleur/data/fleurinp.py", line 364, in _add_path
 |     self.put_object_from_filelike(file1, key, mode='wb')
 | TypeError: put_object_from_filelike() got an unexpected keyword argument 'mode'
```

Of course there might be other things that don't work. The full migration guide can be found [here](https://github.com/aiidateam/aiida-core/wiki/AiiDA-2.0-plugin-migration-guide).

**Comment by broeder-j** [comment]
Should be solved by pull request #121
Will be released soon. Thanks for pointing that out @yakutovicha!
We did already some preparations for aiida 2.0 before, but was not done.
