### ISSUE TITLE
The input `resources.num_machines` shoud be an integer, error

### ISSUE THREAD

**Issue by anoopkcn** [JuDFTteam/aiida-fleur#76]
I'm getting the following  error with the new release version 1.1.0

```bash
2020-02-07 10:05:44 [2317 | REPORT]: [3858|FleurScfWorkChain|start]: INFO: started convergence workflow version 0.4.0
2020-02-07 10:05:45 [2318 | REPORT]: [3858|FleurScfWorkChain|run_fleurinpgen]: INFO: run inpgen
2020-02-07 10:06:14 [2319 | REPORT]: [3858|FleurScfWorkChain|run_fleur]: INFO: run FLEUR
2020-02-07 10:06:14 [2320 | REPORT]: [3858|FleurScfWorkChain|change_fleurinp]: INFO: run change_fleurinp
2020-02-07 10:06:15 [2321 | REPORT]: [3858|FleurScfWorkChain|run_fleur]: INFO: run FLEUR number: 1
2020-02-07 10:06:15 [2322 | REPORT]:   [3869|FleurBaseWorkChain|check_kpts]: WARNING: Changed the number of MPIs per node from 24 to 16 an OMP from 1 to 1. Changed the number of nodes from 2 to 2. Number of k-points is 32.
2020-02-07 10:06:15 [2323 | REPORT]:   [3869|FleurBaseWorkChain|on_except]: Traceback (most recent call last):
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/process_states.py", line 220, in execute
    result = self.run_fn(*self.args, **self.kwargs)
  File "/Users/chand/workbench/devel/aiida-core/aiida/engine/processes/workchains/workchain.py", line 177, in _do_step
    finished, stepper_result = self._stepper.step()
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/workchains.py", line 283, in step
    finished, result = self._child_stepper.step()
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/workchains.py", line 515, in step
    finished, result = self._child_stepper.step()
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/workchains.py", line 283, in step
    finished, result = self._child_stepper.step()
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/workchains.py", line 234, in step
    return True, self._fn(self._workchain)
  File "/Users/chand/workbench/devel/aiida-fleur/aiida_fleur/common/workchain/base/restart.py", line 126, in run_calculation
    calculation = self.submit(self._calculation_class, **inputs)
  File "/Users/chand/workbench/devel/aiida-core/aiida/engine/processes/process.py", line 449, in submit
    return self.runner.submit(process, *args, **kwargs)
  File "/Users/chand/workbench/devel/aiida-core/aiida/engine/runners.py", line 169, in submit
    process = self.instantiate_process(process, *args, **inputs)
  File "/Users/chand/workbench/devel/aiida-core/aiida/engine/runners.py", line 155, in instantiate_process
    return instantiate_process(self, process, *args, **inputs)
  File "/Users/chand/workbench/devel/aiida-core/aiida/engine/utils.py", line 57, in instantiate_process
    process = process_class(runner=runner, inputs=inputs)
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/base/state_machine.py", line 191, in __call__
    inst.transition_to(inst.create_initial_state())
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/base/state_machine.py", line 330, in transition_to
    self.transition_failed(initial_state_label, label, *sys.exc_info()[1:])
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/base/state_machine.py", line 343, in transition_failed
    six.reraise(type(exception), exception, trace)
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/base/state_machine.py", line 314, in transition_to
    self._enter_next_state(new_state)
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/base/state_machine.py", line 374, in _enter_next_state
    self._fire_state_event(StateEventHook.ENTERING_STATE, next_state)
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/base/state_machine.py", line 292, in _fire_state_event
    callback(self, hook, state)
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/processes.py", line 311, in <lambda>
    lambda _s, _h, state: self.on_entering(state))
  File "/Users/chand/workbench/devel/aiida-core/aiida/engine/processes/process.py", line 330, in on_entering
    super().on_entering(state)
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/processes.py", line 604, in on_entering
    call_with_super_check(self.on_create)
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/base/utils.py", line 29, in call_with_super_check
    fn(*args, **kwargs)
  File "/Users/chand/workbench/devel/aiida-core/aiida/engine/processes/process.py", line 320, in on_create
    super().on_create()
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/base/utils.py", line 16, in new_fn
    fn(self, *args, **kwargs)
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/processes.py", line 653, in on_create
    result = self.spec().inputs.validate(self._parsed_inputs)
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/ports.py", line 611, in validate
    validation_error = self.validate_ports(port_values, breadcrumbs_local)
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/ports.py", line 683, in validate_ports
    validation_error = port.validate(port_values.pop(name, UNSPECIFIED), breadcrumbs)
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/ports.py", line 611, in validate
    validation_error = self.validate_ports(port_values, breadcrumbs_local)
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/ports.py", line 683, in validate_ports
    validation_error = port.validate(port_values.pop(name, UNSPECIFIED), breadcrumbs)
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/ports.py", line 611, in validate
    validation_error = self.validate_ports(port_values, breadcrumbs_local)
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/ports.py", line 683, in validate_ports
    validation_error = port.validate(port_values.pop(name, UNSPECIFIED), breadcrumbs)
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/ports.py", line 206, in validate
    result = self.validator(value, self)
  File "/Users/chand/workbench/devel/aiida-core/aiida/engine/processes/calcjobs/calcjob.py", line 91, in validate_resources
    raise exceptions.InputValidationError('the input `resources.num_machines` shoud be an integer.')
aiida.common.exceptions.InputValidationError: the input `resources.num_machines` shoud be an integer.

2020-02-07 10:06:15 [2324 | REPORT]:   [3869|FleurBaseWorkChain|on_terminated]: remote folders will not be cleaned
2020-02-07 10:06:16 [2325 | REPORT]: [3858|FleurScfWorkChain|inspect_fleur]: INFO: inspect FLEUR
2020-02-07 10:06:16 [2326 | REPORT]: [3858|FleurScfWorkChain|control_end_wc]: ERROR: Last Fleur calculation failed with exit status None
2020-02-07 10:06:16 [2327 | REPORT]: [3858|FleurScfWorkChain|on_except]: Traceback (most recent call last):
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/process_states.py", line 220, in execute
    result = self.run_fn(*self.args, **self.kwargs)
  File "/Users/chand/workbench/devel/aiida-core/aiida/engine/processes/workchains/workchain.py", line 177, in _do_step
    finished, stepper_result = self._stepper.step()
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/workchains.py", line 283, in step
    finished, result = self._child_stepper.step()
  File "/Users/chand/pyenvs/aiida/lib/python3.7/site-packages/plumpy/workchains.py", line 234, in step
    return True, self._fn(self._workchain)
  File "/Users/chand/workbench/devel/aiida-fleur/aiida_fleur/workflows/scf.py", line 503, in inspect_fleur
    self.control_end_wc(error)
  File "/Users/chand/workbench/devel/aiida-fleur/aiida_fleur/workflows/scf.py", line 756, in control_end_wc
    self.return_results()
  File "/Users/chand/workbench/devel/aiida-fleur/aiida_fleur/workflows/scf.py", line 630, in return_results
    last_calc_uuid = find_last_in_restart(self.ctx.last_calc)
  File "/Users/chand/workbench/devel/aiida-fleur/aiida_fleur/tools/common_fleur_wf.py", line 667, in find_last_in_restart
    return calls[-1].node.uuid
IndexError: list index out of range

```

**Comment by Tseplyaev** [comment]
@anoopkcn 

Please check the develop branch out and see if the latest commit fixes your problem
